### ISSUE TITLE
Traduction uniforme de tag

### ISSUE THREAD

**Issue by jnavila** [progit-fr/progit#8]
Le mot tag est alternativement traduit en balise et étiquette.  
La traduction communément acceptée semble être étiquette tandis que le glossaire de traduc.org indique plutôt balise.

**Comment by Isammoc** [comment]
Personnellement, au sens git, je pense qu'il faudrait mieux utiliser étiquette.

"tag" ici représente un marqueur sur un commit, dans le sens "mettre une étiquette".
"balise" se rapporte plus sur un tag html, non ?

**Comment by jnavila** [comment]
C'est aussi ce que je pensais mais si on cherche tag sur 

http://glossaire.traduc.org/index.php

on tombe sur des entrées comme release tag -> balise de la version et tagging -> balisage

**Comment by Isammoc** [comment]
Doit-on forcément suivre traduc.org les yeux fermés ?
(Même si la question parait mal tournée, c'est une vraie question)

Mais (pour le moment du moins), je reste sur ma position.
"Balise" est bien pour les randonnées, ou pour les éléments XML, ou encore pour des signaux forts (sticky tag)
"Etiquette" me semble ici plus approprié. On ne modifie pas le commit, on lui appose juste une étiquette.
De plus, cette étiquette peut être déplacée (même si ce n'est pas réellement souhaitable), un peu comme un post-it.

Mais je peux comprendre que l'on doit suivre des conventions... malgré que la traduction s'apparente plus à de l'art qu'à Google Traduction.

J'ai envie de comparer ceci aux lemmings qui sautent de la falaise parce que ceux d'avant passaient par là.
(Si la seule argumentation est traduc.org, bien entendu)

(Attention : la provoc' clairement définie ici, n'est là que pour obtenir un contre-argumentaire, pas pour blesser)

**Comment by jnavila** [comment]
En matière de traduction technique, on cherche les termes précis permettant de faire référence à un concept unique.  Comme dirait l'autre dans les milieux autorisés, on s'autorise à utiliser directement le terme tag en sachant qu'il n'a rien à voir avec le sens général.

Mais ici, on doit faire comprendre le concept. Donc, je ne cherche pas à traduire un terme comme tout le monde le traduit, mais surtout comme tout le monde le comprend.

Et je n'ai pas doctrine particulière concernant les termes, et par extension pas de dévotion à traduc.org. Balise au sens balise maritime pour montrer un cheminement reste valide. Pour te donner raison, je pense que étiquette reste le bon terme. C'est par exemple celui utilisé par TortoiseSVN... Par contre, il n'est pas possible de tagger dans git gui.

Donc va pour étiquette.
